-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 14, 2025 at 09:14 PM
-- Server version: 9.1.0
-- PHP Version: 8.3.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `iskobrasil`
--

-- --------------------------------------------------------

--
-- Table structure for table `event`
--

DROP TABLE IF EXISTS `event`;
CREATE TABLE IF NOT EXISTS `event` (
  `id_e` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `e_name` char(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `e_date_start` date DEFAULT NULL,
  `e_date_stop` date DEFAULT NULL,
  `e_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `e_background_image` char(100) COLLATE utf8mb3_bin DEFAULT NULL,
  UNIQUE KEY `id_e` (`id_e`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `event`
--

INSERT INTO `event` (`id_e`, `e_name`, `e_date_start`, `e_date_stop`, `e_date`, `created_at`, `e_background_image`) VALUES
(1, 'PRÊMIO IBICT – ISKO BRASIL 2025', NULL, NULL, '2025-11-07', '2025-11-14 12:20:19', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `event_assinature`
--

DROP TABLE IF EXISTS `event_assinature`;
CREATE TABLE IF NOT EXISTS `event_assinature` (
  `id_ass` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `ass_name` char(100) COLLATE utf8mb3_bin NOT NULL,
  `ass_location` char(100) COLLATE utf8mb3_bin NOT NULL,
  `ass_reason` char(100) COLLATE utf8mb3_bin NOT NULL,
  `ass_certPem` char(100) COLLATE utf8mb3_bin NOT NULL,
  `ass_keyPem` char(100) COLLATE utf8mb3_bin NOT NULL,
  UNIQUE KEY `id_ass` (`id_ass`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `event_assinature`
--

INSERT INTO `event_assinature` (`id_ass`, `ass_name`, `ass_location`, `ass_reason`, `ass_certPem`, `ass_keyPem`) VALUES
(1, 'Rita do Carmo Laipelt', 'Porto Algre, RS', 'Presidente da ISKO Brasil', 'cert_rita.pem', 'key_rita.pem');

-- --------------------------------------------------------

--
-- Table structure for table `event_certificate`
--

DROP TABLE IF EXISTS `event_certificate`;
CREATE TABLE IF NOT EXISTS `event_certificate` (
  `id_ec` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `ec_event` int DEFAULT NULL,
  `ec_text` longtext COLLATE utf8mb3_bin,
  `ec_ch` int NOT NULL DEFAULT '0',
  `ec_date` date DEFAULT NULL,
  `ec_ass_1` int DEFAULT NULL,
  `ec_ass_2` int DEFAULT NULL,
  `ec_event_id` int DEFAULT NULL,
  UNIQUE KEY `id_ec` (`id_ec`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `event_certificate`
--

INSERT INTO `event_certificate` (`id_ec`, `ec_event`, `ec_text`, `ec_ch`, `ec_date`, `ec_ass_1`, `ec_ass_2`, `ec_event_id`) VALUES
(1, 1, '<h1 style=\"text-align:center; font-size:40px; margin-top:30px;\">CERTIFICADO</h1>\r\n<p>Certificamos que <b>$NOME</b>, participou na qualidade de membro de Comissão Julgadora do $EVENTO, realizado no período de $DATA.</p>', 0, '2025-11-07', 1, 2, 1);

-- --------------------------------------------------------

--
-- Table structure for table `event_certificate_emit`
--

DROP TABLE IF EXISTS `event_certificate_emit`;
CREATE TABLE IF NOT EXISTS `event_certificate_emit` (
  `id_ece` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `ece_person` int NOT NULL,
  `ece_certificate` int NOT NULL,
  `ece_status` int NOT NULL DEFAULT '0',
  UNIQUE KEY `id_ece` (`id_ece`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `event_certificate_emit`
--

INSERT INTO `event_certificate_emit` (`id_ece`, `ece_person`, `ece_certificate`, `ece_status`) VALUES
(1, 1, 1, 0),
(2, 2, 1, 0),
(3, 3, 1, 0),
(4, 4, 1, 0),
(5, 5, 1, 0),
(6, 6, 1, 0),
(7, 7, 1, 0),
(8, 8, 1, 0),
(9, 9, 1, 0),
(10, 10, 1, 0),
(11, 11, 1, 0),
(12, 12, 1, 0),
(13, 13, 1, 0),
(14, 14, 1, 0),
(15, 15, 1, 0),
(16, 16, 1, 0),
(17, 17, 1, 0),
(18, 18, 1, 0),
(19, 19, 1, 0),
(20, 20, 1, 0);

-- --------------------------------------------------------

--
-- Table structure for table `event_people`
--

DROP TABLE IF EXISTS `event_people`;
CREATE TABLE IF NOT EXISTS `event_people` (
  `id_p` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `p_name` char(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `p_email` char(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `p_cpf` char(20) COLLATE utf8mb3_bin DEFAULT NULL,
  `p_email_2` char(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `p_institution` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `id_p` (`id_p`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `event_people`
--

INSERT INTO `event_people` (`id_p`, `p_name`, `p_email`, `p_cpf`, `p_email_2`, `p_institution`, `created_at`) VALUES
(1, 'Andre Vieira de Freitas Araújo', 'armarius.araujo@gmail.com', NULL, NULL, NULL, '2025-11-14 15:06:30'),
(2, 'Benildes Coura Moreira dos Santos Maculan', 'benildes@gmail.com', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(3, 'Brisa Pozzi de Sousa', 'brisa.pozzi@unirio.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(4, 'Carlos Candido de Almeida', 'carlos.c.almeida@unesp.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(5, 'Célia da Consolação Dias', 'celiadias@eci.ufmg.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(6, 'Cibele Araujo Camargo Marques dos Santos', 'cibeleac@usp.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(7, 'Edivanio Duarte de Souza', 'edivanio.duarte@ichca.ufal.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(8, 'Fabiano Ferreira de Castro', 'fabianocastro@ufscar.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(9, 'Fabio Assis Pinho', 'fabio.assis@ufpe.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(10, 'Frederico Mafra', 'professorfredericomafra@gmail.com', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(11, 'Marcio Ferreira da Silva', 'marcio.ferreira@ufma.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(12, 'Marcos Luiz Cavalcanti de Miranda', 'mlmiranda@unirio.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(13, 'Marcos Luiz Mucheroni', 'mucheroni.marcosl@gmail.com', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(14, 'Mário Guido Barité Roqueta', 'mario.barite@fic.edu.uy', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(15, 'Marivalde Moacir Francelin', 'marivalde@usp.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(16, 'Michely Jabala Mamede Vogel', 'michelyvogel@id.uff.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(17, 'Natália Bolfarini Tognoli', 'nataliatognoli@id.uff.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(18, 'Paula Regina Dal\'Evedove', 'dalevedove@ufscar.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(19, 'Rita Laipelt', 'ritacarmo@yahoo.com.br', NULL, NULL, NULL, '2025-11-14 15:09:03'),
(20, 'Rosa Inês de Novais Cordeiro', 'igneznovais@uol.com.br', NULL, NULL, NULL, '2025-11-14 15:09:03');

-- --------------------------------------------------------

--
-- Table structure for table `isko_associado_proposta`
--

DROP TABLE IF EXISTS `isko_associado_proposta`;
CREATE TABLE IF NOT EXISTS `isko_associado_proposta` (
  `id_ap` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `isko_id` varchar(10) COLLATE utf8mb3_bin DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb3_bin NOT NULL,
  `class` tinyint NOT NULL DEFAULT '0',
  `affiliation` varchar(255) COLLATE utf8mb3_bin DEFAULT NULL,
  `is_member` tinyint(1) NOT NULL DEFAULT '0',
  `email` varchar(255) COLLATE utf8mb3_bin NOT NULL,
  `email2` char(50) COLLATE utf8mb3_bin NOT NULL,
  `phone` char(30) COLLATE utf8mb3_bin NOT NULL,
  `type` char(50) COLLATE utf8mb3_bin NOT NULL,
  `address` longtext COLLATE utf8mb3_bin NOT NULL,
  `city` char(50) COLLATE utf8mb3_bin NOT NULL,
  `doc` char(100) COLLATE utf8mb3_bin NOT NULL,
  `updated_at` date DEFAULT NULL,
  PRIMARY KEY (`id_ap`),
  UNIQUE KEY `uq_email` (`email`),
  KEY `idx_class` (`class`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

--
-- Dumping data for table `isko_associado_proposta`
--

INSERT INTO `isko_associado_proposta` (`id_ap`, `isko_id`, `name`, `class`, `affiliation`, `is_member`, `email`, `email2`, `phone`, `type`, `address`, `city`, `doc`, `updated_at`) VALUES
(1, NULL, 'Gustavo Silva Saldanha', 0, 'Instituto Brasileiro de Informação em Ciência e Tecnologia (IBICT)', 0, 'saldanhaquim@gmail.com', 'gustavosaldanha@ibict.br', '21 984079917', 'Pesquisador/a (R$ 330,00)', 'Rua Lauro Muller, 455, 4o andar, Botafogo, Rio de Janeiro, RJ - 22290160', 'Rio de Janeiro, RJ', 'https://drive.google.com/open?id=19mry9yHIS4QIrkRA07ZdrPrPgqDWjp0X', '0000-00-00'),
(2, NULL, 'Rita de Cássia do Vale Caribé', 0, 'Universidade de Brasília- faculdade de ciência da informação', 0, 'rita.caribe@gmail.com', 'rita.caribe@gmail.com', '61999943339', 'Profissional com atuação em Organização do Conheci', 'SMPW quadra 25 conjunto 3 lote 1 casa D', 'Brasília-DF', 'https://drive.google.com/open?id=1X5vqLpg-FfXYxttWfARhuVNnpUOEqv2d', '0000-00-00'),
(3, NULL, 'Maria José Veloso da Costa Santos', 0, 'UFRJ', 0, 'msantos1402@facc.ufrj.br', 'msantos1402@facc.ufrj.br', '(21) 981114959', 'Aposentado/a (R$ 110,00)', 'Rua Toneleros, 43/703', 'Rio de janeiro - RJ', 'https://drive.google.com/open?id=1xIXfiAT72uOnMphKE3lmup6ICtOmhW1F', '0000-00-00'),
(4, NULL, 'Giovana Deliberali Maimone', 0, 'USP', 0, 'gdmaimone@usp.br', 'gdmaimone@usp.br', '15997377091', 'Professor/a (R$ 330,00)', 'Avenida onze de agosto, 15', 'Tietê / SP', 'https://drive.google.com/open?id=1xX9PLsgcHY4_BPaL8GqpVu9O_E1tzux7', '0000-00-00'),
(5, NULL, 'Ananda Feix Ribeiro', 0, 'UFRGS', 0, 'ananda.feix@gmail.com', 'ananda.feix@gmail.com', '51993740297', 'Estudante (R$ 110,00)', 'Rua Dona Madalena, 221', 'Porto Alegre/RS', 'https://drive.google.com/open?id=1EdfeVfMiaLN5-bhxhWqvuEWnw12kxtSn', '0000-00-00'),
(6, NULL, 'Lais Pereira de Oliveira', 0, 'Universidade Federal de Goiás (UFG)', 0, 'laispereira2@ufg.br', 'laispereira2@ufg.br', '(62) 99152-4624', 'Professor/a (R$ 330,00)', 'Rua Tupi, Qd. 16, Lt. 04 - Setor Belo Horizonte Sul', 'Aparecida de Goiânia - Goiás', 'https://drive.google.com/open?id=1Aot-_PZf38cSivHDn3_si3A-hRZw6u_L', '0000-00-00'),
(7, NULL, 'Rodrigo de Sales', 0, 'Universidade Federal de Santa Catarina', 0, 'rodrigo.sales.s@gmail.com', 'rodrigo.sales.s@gmail.com', '48 99633-2155', 'Professor/a (R$ 330,00)', 'Av. Hercílio Luz, 881, apt. 602. CEP 88020-001', 'Flrianópolis, SC', 'https://drive.google.com/open?id=1PsvmURWN_f9iG6_JTatHUxCTtxxUu_I8', '0000-00-00'),
(8, NULL, 'Cristina Dotta Ortega', 0, 'UFMG', 0, 'crortega1968@gmail.com', 'ortega@eci.ufmg.br', '31994069844', 'Professor/a (R$ 330,00)', 'Rua Desembargador Paula Mota, 950 apto. 201', 'Belo Horizonte/MG', 'https://drive.google.com/open?id=1jom_qc78qSbLInPaqlSbiS_-jMCUrvgY', '0000-00-00'),
(9, NULL, 'Camila Mariana Aparecida da Silva', 0, 'Universidade Federal de Minas Gerais', 0, 'camilamas.silva@gmail.com', 'camilamas.silva@gmail.com', '31993061121', 'Profissional com atuação em Organização do Conheci', 'Rua Desembargador Paulo Mota, 1040 - ap 402', 'Belo Horizonte - Minas Gerais', 'https://drive.google.com/open?id=1bqlu5aZTxs38wuxtAs6Uypner1wp_jxi', '0000-00-00'),
(10, NULL, 'Johanna Wilhelmina Smit', 0, 'USP', 0, 'cbdjoke@usp.br', 'cbdjoke@usp.br', '1199323-4857', 'Aposentado/a (R$ 110,00)', 'Rua Dr Teodoro Quartim Barbosa 223 B, ap. 72 - CEP 05352-050', 'São Pau7lo, SP', 'https://drive.google.com/open?id=1wFnS0wiVdiJBXlz2KJxSxfEEi58pINFD', '0000-00-00'),
(11, NULL, 'Carla Maria Martellote Viola', 0, 'IBICT', 0, 'viola.carla@gmail.com', 'viola.carla@gmail.com', '21972398649', 'Aposentado/a (R$ 110,00)', 'Rua Guilherme Marconi 74 apt 902\nCentro - Brasil', 'Rio de Janeiro', 'https://drive.google.com/open?id=1lfkZQPQYwyLuTp9vTV_tuRpBRjPUNJIZ', '0000-00-00'),
(12, NULL, 'Benildes Coura Moreira dos Santos Maculan', 0, 'Universidade Federal de Minas Gerais (UFMG)', 0, 'benildes@gmail.com', 'benildes@gmail.com', '31 98652-4245', 'Professor/a (R$ 330,00)', 'Av. Pres. Antônio Carlos, 6627, Escola de Ciência da Informação, Pampulha', 'Belo Horizonte. MG', 'https://drive.google.com/open?id=1nz6GvQ-03geKBcyhOE6xSupSF3tiLWPQ', '0000-00-00'),
(13, NULL, 'Brisa Pozzi de Sousa', 0, 'Unirio', 0, 'brisa.pozzi@unirio.br', 'brisa.pozzi@unirio.br', '(21)96914-6575', 'Professor/a (R$ 330,00)', 'Rua Tiradentes, nº 122 - apto 703 - Ingá', 'Niterói, RJ', 'https://drive.google.com/open?id=1SlFiMsvHzRKsHTYlDPlkooHO4jhSJ7q1', '0000-00-00'),
(14, NULL, 'Jéssica dos Santos Gonçalves', 0, 'Companhia de Pesquisa de Recursos Minerais (SGB/CPRM)', 0, 'jessica.goncalves@sgb.gov.br', 'jessgoncal@gmail.com', '(21)97589-4999', 'Profissional com atuação em Organização do Conheci', 'Rua Pereira da Silva, 270, Apt. 404, Laranjeiras, CEP: 22221-140', 'Rio de Janeiro - RJ', 'https://drive.google.com/open?id=1wqWom71BhEx4fnEMEnVRQ5tQDxEq-mMM', '0000-00-00'),
(15, NULL, 'Gilberto Gomes Cândido', 0, 'Universidade Federal do Pará', 0, 'ggcandido@ufpa.br', 'ggcandido@ufpa.br', '91992091887', 'Professor/a (R$ 330,00)', 'Travessa Timbó, 1890, Apto 1007', 'Belém/Pará', 'https://drive.google.com/open?id=1pijNfQnfXFT6Rh4H5xPlHiwBiPxhs7RR', '0000-00-00'),
(16, NULL, 'Clarice Luzia R Casoni', 0, 'UNIVERSIDADE ESTADUAL DE LONDRINA', 0, 'claricecasoni@gmail.com', 'claricecasoni@gmail.com', '43999039060', 'Estudante (R$ 110,00)', 'RUA TAKABUMI MURATA, 555\nCASA 48, COND VILLAGE PREMIUM', 'LONDRINA -  PARANA', 'https://drive.google.com/open?id=1l7cJCljqar2p7jcUbnIMJt6HH2Y9VU8f', '0000-00-00'),
(17, NULL, 'Raíssa Yuri Hamanaka', 0, 'Sofa Digital', 0, 'raissa0201@gmail.com', 'raissa0201@gmail.com', '(31) 99522-7707', 'Profissional com atuação em Organização do Conheci', 'Rua Gloriosa, 260, bairro Jardinópolis, CEP30.510-490', 'Belo Horizonte/Minas Gerais', 'https://drive.google.com/open?id=1xJmsj1M6s4_LVgyz3DNrAeK70DI69Ujd', '0000-00-00'),
(18, NULL, 'Carla Beatriz Marques Felipe', 0, 'UFRJ', 0, 'felipecarla12@gmail.com', 'felipecarla12@gmail.com', '21981631966', 'Professor/a (R$ 330,00)', 'Rua João Afonso, 86 - Humaitá 222-61040', 'Rio de janeiro-Rio de Janeiro', 'https://drive.google.com/open?id=1wsEvLItCdnPIHqpewPxzGnMworKT3b4h', '0000-00-00'),
(19, NULL, 'Fernanda Farinelli', 0, 'FCI UnB', 0, 'fernanda.farinelli@gmail.com', 'fernanda.farinelli@unb.br', '31998235958', 'Professor/a (R$ 330,00)', 'SQB 212 BL. A, APT 112, 70.864-010', 'Brasília/DF', 'https://drive.google.com/open?id=1Vgv7U-Ew6loajQBoW2j-lTvvCZ6VlneD', '0000-00-00'),
(20, NULL, 'Rafael Rodrigo do Carmo Batista', 0, 'Universidade Federal de Santa Catarina', 0, 'rafael.rcb3@gmail.com', 'rafael.bibufsm@gmail.com', '55981150276', 'Estudante (R$ 110,00)', 'Rua Machado de Assis, n.81', 'Santa Maria, RS', 'https://drive.google.com/open?id=1Wb6blCeONXIwhVDvjsP75jL-Bo_mCZVD', '0000-00-00'),
(21, NULL, 'Rita do Carmo Ferreira Laipelt', 0, 'Universidade Federal do Rio Grande do Sul (UFRGS)', 0, 'rlaipelt@gmail.com', 'ritacarmo@yahoo.com.br', '51 984236099', 'Professor/a (R$ 330,00)', 'Avenida Protásio Alves, 910. Apto. 22', 'Porto Alegre/ RS', 'https://drive.google.com/open?id=16KtClqLQOfvMJuTrEJNdOgAH2IS9SEMN', '0000-00-00'),
(22, NULL, 'Michely Jabala Mamede Vogel', 0, 'Universidade Federal Fluminense', 0, 'michelyvogel@id.uff.br', 'michelyvogel@id.uff.br', '21982064162', 'Professor/a (R$ 330,00)', 'Rua Maria Luzia Gomes da Costa, s/n. Quadra 57 Lote 4 - Engenho do Mato - CEP 24344541', 'Niterói/RJ', 'https://drive.google.com/open?id=1uizOc-uWJFgRXQCDGX59hUYasjpU7uUI', '0000-00-00'),
(23, NULL, 'ADRIANA OLINTO BALLESTE', 0, 'Instituto Brasileiro de Informação em Ciência e Tecnologia', 0, 'adriballeste@gmail.com', 'adriballeste@gmail.com', '21 981221400', 'Profissional com atuação em Organização do Conheci', 'Rua General Glicério 400, 802', 'Rio de Janeiro - Rio de Janeiro', 'https://drive.google.com/open?id=1BIA2kbDwNfvr8OMcOfz2gx68E-QkAf5q', '0000-00-00'),
(24, NULL, 'Patrícia Nascimento Silva', 0, 'Universidade Federal de Minas Gerais', 0, 'patricians.prof@gmail.com', 'patricians.prof@gmail.com', '(31)992726279', 'Professor/a (R$ 330,00)', '32235-380', 'Contagem - MG', 'https://drive.google.com/open?id=1ifxmKik7w1wEJtyqw1kOl-_vpgzR8uH_', '0000-00-00'),
(25, NULL, 'VANIA MARA ALVES LIMA', 0, 'UNIVERSIDADE DE SÃO PAULO', 0, 'vamal@usp.br', 'vamal@usp.br', '11 99777-4679', 'Professor/a (R$ 330,00)', 'RUA CORREGGIO, 295  APTO  51    CEP 05630-020', 'SÃO PAULO -SP', 'https://drive.google.com/open?id=1_U9H4CrSTMUbKFd8koC2YPD6fFw53bst', '0000-00-00'),
(26, NULL, 'Caliel Cardoso de Oliveira', 0, 'ORCALAB', 0, 'caliel.co@gmail.com', 'caliel.co@gmail.com', '51981730776', 'Pesquisador/a (R$ 330,00)', 'Rua Frei Rafael, 57, Salgado Filho - CEP 94020330', 'Gravataí, RS', 'https://drive.google.com/open?id=1vcIg7TczRoDxZnkKSm8QCAiQtJk5iRt-', '0000-00-00'),
(27, NULL, 'Andre Vieira de Freitas Araujo', 0, 'Universidade Federal do Paraná', 0, 'armarius.araujo@gmail.com', 'armarius.araujo@gmail.com', '(11) 98449-6722', 'Professor/a (R$ 330,00)', 'Av. João Gualberto, 381, apto 201, Alto da Glória, CEP 80030-000', 'Curitiba - PR', 'https://drive.google.com/open?id=1zUdPfPX3iV0I-FowMYGhhkTCb2-GEtqB', '0000-00-00'),
(28, NULL, 'Brígida Maria Nogueira Cervantes', 0, 'Universidade Estadual de Londrina', 0, 'brigidacervantes@gmail.com', 'brigidacervantes@gmail.com', '(43) 99945-2910', 'Professor/a (R$ 330,00)', 'Rua Antônio Fabrício Ribeiro, 137 - Quadra 12 - Lote 33 - Sun Lake Residence - \nCEP 86058-272', 'Londrina / Paraná', 'https://drive.google.com/open?id=1LebrN8kAsW6YoQmQTBq9esmdwTa_h8iG', '0000-00-00'),
(29, NULL, 'GUILHERME ATAIDE DIAS', 0, 'UFPB', 0, 'guilhermeataide@gmail.com', 'guilhermeataide@gmail.com', '83 9 9305 0717', 'Professor/a (R$ 330,00)', 'RUA MANOEL GUALBERTO 66 AP 1102  - MIRAMAR', 'JOÃO PESSOA - PB', 'https://drive.google.com/open?id=18OJh5jWh6jYX9jwjZg7NdK2q0bPhkPdV', '0000-00-00'),
(30, NULL, 'Juliana Cristhine Schifino Santos Jardim Pereira', 0, 'Universidade Federal do Rio Grande do Sul', 0, 'jujujardim@gmail.com', 'jujujardim@gmail.com', '51996445447', 'Estudante (R$ 110,00)', 'Rua Menezes Paredes, 145. Bairro Nonoai. Cep: 90830-070', 'Porto Alegre - Rio Grande do Sul', 'https://drive.google.com/open?id=1wleAWIMIDQY-BtZm6WHjAF7i_dKBpLmp', '0000-00-00'),
(31, NULL, 'Benjamin Luiz Franklin', 0, 'Universidade Estadual de Londrina', 0, 'belfra@gmail.com', 'belfra@gmail.com', '43 996690707', 'Professor/a (R$ 330,00)', 'Rua Jerusalém 200, apt 804.  CEP: 86050520', 'Londrina, Paraná', 'https://drive.google.com/open?id=18sZaQb0gSXd75xaQ4cVubYEkJwpYuJh4', '0000-00-00'),
(32, NULL, 'Patrícia Mallmann Souto Pereira', 0, 'UFRJ e UFRGS', 0, 'patriciamall@facc.ufrj.br', 'patriciamall@facc.ufrj.br', '(21)99988-7679', 'Pesquisador/a (R$ 330,00)', 'Praça Eugênio Jardim, 1, ap. 601', 'Rio de Janeiro/RJ', 'https://drive.google.com/open?id=1f6ROENSj-CIkKtbcaEdCcrPsRt9ZX-i-', '0000-00-00'),
(33, NULL, 'Januário Albino Nhacuongue', 0, 'Universidade Federal de São Carlos (UFSCar)', 0, 'januario@ufscar.br', 'januario@ufscar.br', '14996823496', 'Professor/a (R$ 330,00)', 'Rua São Sebastião, 2467', 'São Carlos - SP', 'https://drive.google.com/open?id=1hG9ZbYOtzmMD59r0n2F5qHyOGXkQB0x7', '0000-00-00'),
(34, NULL, 'Rafael Aparecido Moron Semidão', 0, 'Universidade Federal do Rio Grande - FURG', 0, 'rafaelsemidao@gmail.com', 'rafaelsemidao@gmail.com', '14981744624', 'Professor/a (R$ 330,00)', 'Av. Presidente Vargas, 285. Bloco M1, Apto. 103. Cep: 96202-336', 'Rio Grande/RS', 'https://drive.google.com/open?id=12tEtm3dFnWklcUpxZf5ndHlUC8sTSWQY', '0000-00-00'),
(35, NULL, 'Nanci E. Oddone', 0, 'UNIRIO', 0, 'neoddone@gmail.com', 'neoddone@gmail.com', '21999617580', 'Professor/a (R$ 330,00)', 'Av Marechal Rondon, 1155\nBloco 2, apto 702\nRocha\n20950-901', 'Rio de Janeiro', 'https://drive.google.com/open?id=1WO181izcg7hIY0dQlwwWdEEnuIhXN3Rq', '0000-00-00'),
(36, NULL, 'Luiza Hiromi Arao', 0, 'Universidade Federal do Estado do Rio de Janeiro', 0, 'lhiromi.arao@gmail.com', 'lhiromi.arao@gmail.com', '21 987775886', 'Estudante (R$ 110,00)', 'Av. Prefeito Dulcídio Cardoso, 2500, bloco 3, apto 404', 'Rio de Janeiro', 'https://drive.google.com/open?id=16vjBlvTF7gkuloYQ9AEu5T63y5WCHGiu', '0000-00-00'),
(37, NULL, 'Evelin Melo Mintegui', 0, 'FURG - Universidade Federal do Rio Grande', 0, 'eminteguimail@gmail.com', 'eminteguimail@gmail.com', '53991784208', 'Professor/a (R$ 330,00)', 'Dr. Cassiano, 37, ap 301, 96015-700', 'Pelotas RS', 'https://drive.google.com/open?id=1ENe8L8zMzLWNgAZCGFL_CHGwywC6e_MY', '0000-00-00'),
(38, NULL, 'Maria Helena Sachi do Amaral', 0, 'Universidade Federal de São Carlos', 0, 'helena.amaral@ufscar.br', 'helena.amaral@ufscar.br', '19987600250', 'Profissional com atuação em Organização do Conheci', 'Rua Sebastião Boava, 181 - Jardim Encosta do Sol, CEP 13604-150', 'Araras, SP', 'https://drive.google.com/open?id=1NWcTCO5ycl3z1ue9QUkQXhNTUEiq_7or', '0000-00-00'),
(39, NULL, 'Emilly Leticia Vieira de Souza', 0, 'Universidade Federal de Goiás', 0, 'emillysouza@ufg.br', 'emillysouza@ufg.br', '62993232831', 'Professor/a (R$ 330,00)', 'Rua SC 7 Qd 11 Lt17 Apt 05 Goiânia 2 Cep 74665630', 'Goiânia - Goiás', 'https://drive.google.com/open?id=1jBJjSsAbySvTn65uNBrEWCnrfXYvBLCo', '0000-00-00'),
(40, NULL, 'Rosana Portugal Tavares de Moraes', 0, 'Universidade Federal Fluminense', 0, 'rosanaportugal@id.uff.br', 'rosanaportugal@id.uff.br', '21 988951272', 'Professor/a (R$ 330,00)', 'Rua Domingues de Sá, 240, apt. 401, Icaraí, Niterói, RJ', 'Niterói, Rio de Janeiro', 'https://drive.google.com/open?id=1uDNy8eAjvciO_pyXY2Me2X93R-9_DKDS', '0000-00-00'),
(41, NULL, 'Amanda Marissa Soares da Silva', 0, 'Universidade Estadual Paulista', 0, 'amandamarissa1@gmail.com', 'amandamarissa1@gmail.com', '91983024884', 'Estudante (R$ 110,00)', 'Cep 66813005', 'Belém - Pará', 'https://drive.google.com/open?id=1QxvFCwG6Aym998Esvj84Fwm30iJL67lB', '0000-00-00'),
(42, NULL, 'Mariângela Spotti Lopes Fujita', 0, 'UNESP - Campus de Marília', 0, 'mariangela.fujita@unesp.br', 'mariangela.fujita@unesp.br', '11948292022', 'Aposentado/a (R$ 110,00)', 'Rua Sebastião Braz de Oliveira, 103, Jardim Acapulco, Marília, SP, 17525-300', 'Marília, SP', 'https://drive.google.com/open?id=1JQFq2ZQrOcPQWpUxkZbSzOLLuGOh6EZ0', '0000-00-00'),
(43, NULL, 'Marcos Luiz Cavalcanti Miranda', 0, 'Universidade Federal do Estado do Rio de Janeiro - UNIRIO', 0, 'marcos.miranda@edu.unirio.br', 'mlmiranda@unirio.br', '21967173772', 'Professor/a (R$ 330,00)', 'Rua Domingos Ferreira nº 34 apt. 802 - Copacabana - CEP 22.050-012', 'Rio de Janeiro - RJ', 'https://drive.google.com/open?id=1OMwmab941cjbogkdPW-evC1ld0xfjD1J', '0000-00-00'),
(44, NULL, 'Fabio Assis Pinho', 0, 'Universidade Federal de Pernambuco', 0, 'fabio.assis@ufpe.br', 'fabio.assis@ufpe.br', '81992430892', 'Professor/a (R$ 330,00)', 'Rua Adelino Frutuoso, 199 - Apto. 1303A - Bairro Cordeiro', 'Recife - Pernambuco', 'https://drive.google.com/open?id=1yfSfzGGSptb03f2cs6eyOKIu_cntRRcM', '0000-00-00'),
(45, NULL, 'Samuel Santos da Rosa', 0, 'Prefeitura Municipal de Triunfo/RS', 0, 'samuel.sdrosa@gmail.com', 'samuel.sdrosa@gmail.com', '51996703504', 'Profissional com atuação em Organização do Conheci', 'Rua João de Deus, nº 130, Bairro Passo da Aldeia - CEP 95860-000', 'Taquari / Rio Grande do Sul', 'https://drive.google.com/open?id=1K8N4YjxAlquY4us8rEksX01tzzcwHDPR', '0000-00-00'),
(46, NULL, 'Luciana Kramer Pereira', 0, 'PGE-RS', 0, 'lucianakramer@gmail.com', 'lucianakramer@gmail.com', '51 984399345', 'Profissional com atuação em Organização do Conheci', 'Rua Bento Manoel Ribeiro, 200, Santo Onofre', 'Viamão / RS', 'https://drive.google.com/open?id=1h7p0QqQWGeZP4SrnfXPJZoNEWgWGmzk-', '0000-00-00'),
(47, NULL, 'Zaira Regina Zafalon', 0, 'UFSCar', 0, 'zzafalon@gmail.com', 'zzafalon@gmail.com', '1633066900', 'Professor/a (R$ 330,00)', 'R. São Paulo, 260 - Vila Monteiro - CEP 13560-340', 'São Carlos / SP', 'https://drive.google.com/open?id=1q03TvzJRUX49LQco6wYxN_-GzO26MupI', '0000-00-00'),
(48, NULL, 'Bruno Henrique Machado', 0, 'Universidade Federal do Rio Grande - FURG, Instituto de Ciências Humanas e da Informação - ICHI.', 0, 'machadobrunohenrique@gmail.com', 'machadobrunohenrique@furg.br', '(017)997465386', 'Professor/a (R$ 330,00)', 'Avenida Presidente Vargas, n. 285, bloco C1, Apto 201.  CEP: 96202-336', 'Rio Grande- Rio Grande do Sul.', 'https://drive.google.com/open?id=1HCeP9VXwj8mI4egVPla7DTFxc3Z5gNKw', '0000-00-00'),
(49, NULL, 'Ana Paula Scorsatto Portela', 0, 'PGE-RS', 0, 'nicappportela@gmail.com', 'nicappportela@gmail.com', '51997316959', 'Profissional com atuação em Organização do Conheci', 'Rua Granadas 420,Rainha do Mar', 'Xangrilá', 'https://drive.google.com/open?id=12_I4lgrIEipjEgnse4y--0VR2JIYQwDV', '0000-00-00'),
(50, NULL, 'ELISANGELA CRISTINA AGANETTE', 0, 'UFMG', 0, 'elisangelaaganette@gmail.com', 'ELISANGELAAGANETTE@GMAIL.COM', '31999321936', 'Profissional com atuação em Organização do Conheci', 'RUA ANTONIO PAULINO DE CASTRO 623 -AP 501', 'MG', 'https://drive.google.com/open?id=1UQ_sH67bgSrGfDe5KSQv1jH0ldaSdK1P', '0000-00-00'),
(51, NULL, 'EVALDO DE OLIVEIRA DA SILVA', 0, 'Centro Universitário UniAcademia', 0, 'evaldo.oliveira@gmail.com', 'evaldo.oliveira@gmail.com', '32991197001', 'Profissional com atuação em Organização do Conheci', 'R OLIMPIO REIS, 283 AP 801. Bairro SANTA HELENA. CEP 36015-170. Juiz de Fora. Minas Gerais.', 'Juiz de Fora, Minas Gerais.', 'https://drive.google.com/open?id=1xjN_e0w3lLHLq_1Y39w51tFZhVl7lWLm', '0000-00-00'),
(52, NULL, 'Luciana de Souza Gracioso', 0, 'UFSCaR', 0, 'iskobrazil@gmail.com', 'luciana@ufscar.br', '16981337729', 'Professor/a (R$ 330,00)', 'Rua Miguel Petroni, 4900, casa 45, Res. Eldorado', 'São Carlos, SP', 'https://drive.google.com/open?id=1zUghjFLUC0e_7Zr2bNznA-qiGB_1yJxp', '0000-00-00'),
(53, NULL, 'CRISTINA RIBEIRO DOS SANTOS', 0, 'Universidade Estadual de Londrina', 0, 'cristina.ribeiro@uel.br', 'cristina.ribeiro@uel.br', '43996339540', 'Professor/a (R$ 330,00)', 'Rua Rio Paranapanema, 42', 'Paraná', 'https://drive.google.com/open?id=1YQLLijrPB95bQ05LwtP92UwzmYsBxTv9', '0000-00-00'),
(54, NULL, 'Daniela Lucas da Silva Lemos', 0, 'Universidade Federal do Espírito Santo', 0, 'daniela.l.silva@ufes.br', 'daniela.l.silva@ufes.br', '27997754151', 'Professor/a (R$ 330,00)', 'Rua Affonso Cláudio, n.77, apto 302. Praia do Canto.', 'Vitória/ES', 'https://drive.google.com/open?id=1OPoggvSam1MyEGK0DUfWeBrmoVXgB4Wn', '0000-00-00'),
(55, NULL, 'Sergio de Castro Martins', 0, 'Universidade Federal do Rio de Janeiro', 0, 'sergiomartins@facc.ufrj.br', 'sergiomartins@facc.ufrj.br', '21991052352', 'Pesquisador/a (R$ 330,00)', 'Rua Comendador Queiroz, 37 ap 603 - Icaraí - CEP 24230-220', 'Niterói, RJ', 'https://drive.google.com/open?id=1lVn3bXYz5vtaT-CPFCYWojA8TeSh9-gj', '0000-00-00'),
(56, NULL, 'Frederico Cesar Mafra Pereira', 0, 'Universidade Federal de Minas Gerais', 0, 'professorfredericomafra@gmail.com', 'professorfredericomafra@gmail.com', '(31) 9 9954-2722', 'Profissional com atuação em Organização do Conheci', 'Rua Doutor Rubens Guimarães, 310 - ap.504 - Bairro Castelo. CEP: 30.840-430', 'Belo Horizonte, Minas Gerais', 'https://drive.google.com/open?id=11wQQWxVx3WPgipe050CPQTadAHz9aSGm', '0000-00-00'),
(57, NULL, 'Valdirene Pereira da Conceição', 0, 'Universidade Federal do Maranhão (UFMA)', 0, 'valdirene.pc@ufma.br', 'valdirene.pc@ufma.br', '(98)98431-3106', 'Professor/a (R$ 330,00)', 'Rua A, Ala D, Casa 03 - Residencial São Domingos I - Cohama', 'São Luís -MA', 'https://drive.google.com/open?id=1oBiG4L8v0ybJT3OC6gPbhi7V89iH3ViI', '0000-00-00'),
(58, NULL, 'Bruna Bomfim Lessa dos Santos', 0, 'Universidade Federal da Bahia', 0, 'lessbruna@gmail.com', 'lessbruna@gmail.com', '71992067458', 'Pesquisador/a (R$ 330,00)', 'Rua Érico Veríssimo, 90, Itaigara Cep.41815-340', 'Salvador/Bahia', 'https://drive.google.com/open?id=15qOdann5aCH3On_TIpO81kLjGsPs1ITI', '0000-00-00'),
(59, NULL, 'Gercina Ângela de Lima', 0, 'Universidade Federal de Minas Gerais', 0, 'limagercina@gmail.com', 'limagerccina@gmail.com', '31992221771', 'Professor/a (R$ 330,00)', 'Rua Lavras, 424\nApto 301', 'Belo Horizonte - Minas Gerais', 'https://drive.google.com/open?id=1R48aw0-0Kb9ZqzFWiH834AGoROQVEAHA', '0000-00-00'),
(60, NULL, 'Fabiano Ferreira de Castro', 0, 'Universidade Federal de São Carlos (UFSCar)', 0, 'fabianocastro@ufscar.br', 'fabianocastro@ufscar.br', '(16)981025285', 'Pesquisador/a (R$ 330,00)', 'Rua Francisca Paula de Jesus Izabel, 113, Parque dos Timburis - CEP: 13569-702', 'São Carlos/SP', 'https://drive.google.com/open?id=1E2G3R0n9k4qxpRTUMAC9yqecD0MiFaHJ', '0000-00-00'),
(61, NULL, 'Roberta Pinto Medeiros', 0, 'Universidade Federal do Rio Grande - FURG', 0, 'roberta.furg@gmail.com', 'roberta.furg@gmail.com', '53 981143346', 'Professor/a (R$ 330,00)', 'Av Juscelino K de Oliveira, 2200, 4A, 104, CEP 96075-810', 'Pelotas-RS', 'https://drive.google.com/open?id=1VnSeTKldNL4MS_k0dY00Ck3Zr-hpTeSX', '0000-00-00'),
(62, NULL, 'Marivalde Moacir Francelin', 0, 'Universidade de São Paulo', 0, 'marivalde@usp.br', 'marivalde@usp.br', '15997497293', 'Professor/a (R$ 330,00)', 'Avenida Engenheiro Heitor Antônio Eiras Garcia, 79. Apartamento 43, Bloco B. Jardim Esmeralda. 05588-000', 'São Paulo. SP', 'https://drive.google.com/open?id=1mJfoePXDQfN_KeDEPfxvwray8NUmlQwl', '0000-00-00'),
(63, NULL, 'ILVANA SOUSA DO AMARAL', 0, 'UNIRIO', 0, 'ilvana.amaral@gmail.com', 'ilvana.amaral@edu.unirio.br', '21981034778', 'Profissional com atuação em Organização do Conheci', 'Rua Doutor Renato Rocco\n81', 'Rio de Janeiro', 'https://drive.google.com/open?id=1AtzYGV2MOpeve8XNqBQmkdYmqyzl3eUz', '0000-00-00'),
(64, NULL, 'Cibele Araujo Camargo Marques dos Santos', 0, 'Escola de Comunicações e Artes. Universidade de São Paulo', 0, 'cibeleac@usp.br', 'cibeleac@usp.br', '11 98046-6014', 'Pesquisador/a (R$ 330,00)', 'Rua Alfredo Mendes da Silva, 395\n161/A5', 'São Paulo SP', 'https://drive.google.com/open?id=19d082J9SizSzdj6mzQ9iHQExLSq7_Q1p', '0000-00-00'),
(65, NULL, 'FELIPE AUGUSTO ARAKAKI', 0, 'UnB', 0, 'fe.arakaki@gmail.com', 'fe.arakaki@gmail.com', '61996134442', 'Professor/a (R$ 330,00)', 'SQN 212, bloco A, 610, apartamento, Asa Norte.  CEP 70864-010', 'Brasília/DF', 'https://drive.google.com/open?id=14c35omZM9H2AFPhDBY-KehGm5efopAXZ', '0000-00-00'),
(66, NULL, 'Claudio Jose Silva Ribeiro', 0, 'Unirio', 0, 'claudio.ribeiro@unirio.br', 'claudio.ribeiro@unirio.br', '(21)981115499', 'Pesquisador/a (R$ 330,00)', 'Rua Prudente de Morais, 750/401 - Ipanema', 'Rio de Janeiro - RJ', 'https://drive.google.com/open?id=1UFi2XW8xeTZZGNi8JDa-D_d0HvMxAztV', '0000-00-00');

-- --------------------------------------------------------

--
-- Table structure for table `isko_categoria`
--

DROP TABLE IF EXISTS `isko_categoria`;
CREATE TABLE IF NOT EXISTS `isko_categoria` (
  `id_c` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_classe` char(20) NOT NULL,
  `c_anuidade` float NOT NULL DEFAULT '0',
  UNIQUE KEY `id_c` (`id_c`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `isko_categoria`
--

INSERT INTO `isko_categoria` (`id_c`, `c_classe`, `c_anuidade`) VALUES
(1, 'Estudante', 110),
(2, 'Pesquisador', 330),
(3, 'Aposentado', 110),
(4, 'Profissional', 110);

-- --------------------------------------------------------

--
-- Table structure for table `isko_cms`
--

DROP TABLE IF EXISTS `isko_cms`;
CREATE TABLE IF NOT EXISTS `isko_cms` (
  `id_ms` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `ms_user` int NOT NULL,
  `ms_subject` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ms_message` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ms_attached` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `ms_data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ms_status` int NOT NULL DEFAULT '0',
  UNIQUE KEY `id_ms` (`id_ms`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `isko_cms`
--

INSERT INTO `isko_cms` (`id_ms`, `ms_user`, `ms_subject`, `ms_message`, `ms_attached`, `ms_data`, `ms_status`) VALUES
(48, 67, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Franciele Marques Redigolo</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:29</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_66.pdf\"]', '2024-05-30 20:18:29', 0),
(49, 25, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Gustavo Silva Saldanha</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:36</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_24.pdf\"]', '2024-05-30 20:18:36', 0),
(50, 26, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Hugo Figueiredo Mafra</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:40</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_25.pdf\"]', '2024-05-30 20:18:40', 0),
(51, 36, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Luciana de Souza Gracioso\n </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:43</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_35.pdf\"]', '2024-05-30 20:18:43', 0),
(52, 70, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Maíra Fernandes Alencar</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:46</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_69.pdf\"]', '2024-05-30 20:18:46', 0),
(53, 37, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Marcos Luiz Cavalcanti de Miranda</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:51</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_36.pdf\"]', '2024-05-30 20:18:51', 0),
(54, 40, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Mariângela Spotti Lopes Fujit</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:54</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_39.pdf\"]', '2024-05-30 20:18:54', 0),
(55, 42, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Marivalde Moacir Francelin</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:18:57</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_41.pdf\"]', '2024-05-30 20:18:57', 0),
(56, 43, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Míriam Gontijo de Moraes</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:33</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_42.pdf\"]', '2024-05-30 20:19:33', 0),
(57, 45, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Nanci Elizabeth Oddone</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:37</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_44.pdf\"]', '2024-05-30 20:19:37', 0),
(58, 47, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Rafael Aparecido Moron Semidão</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:40</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_46.pdf\"]', '2024-05-30 20:19:40', 0),
(59, 48, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Raimundo Nonato Macedo dos Santos </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:43</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_47.pdf\"]', '2024-05-30 20:19:43', 0),
(60, 55, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Rogério Aparecido Sá Ramalho</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:46</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_54.pdf\"]', '2024-05-30 20:19:46', 0),
(61, 56, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Rosa Inês de Novais Cordeiro </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:50</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_55.pdf\"]', '2024-05-30 20:19:50', 0),
(62, 60, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Sergio de Castro Martins </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:54</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_59.pdf\"]', '2024-05-30 20:19:54', 0),
(63, 61, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Suellen Oliveira Milani</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:19:56</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_60.pdf\"]', '2024-05-30 20:19:56', 0),
(64, 65, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Vânia Mara Alves Lima</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:20:00</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_64.pdf\"]', '2024-05-30 20:20:00', 0),
(65, 68, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Walter Moreira</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:20:03</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_67.pdf\"]', '2024-05-30 20:20:03', 0),
(66, 50, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Rene Faustino Gabriel Junior</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:33</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_49.pdf\"]', '2024-05-30 20:37:33', 0),
(67, 21, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Fabio Assis Pinho  </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:36</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_20.pdf\"]', '2024-05-30 20:37:36', 0),
(68, 19, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Evelyn Goyannes Dill Orrico</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:39</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_18.pdf\"]', '2024-05-30 20:37:39', 0),
(69, 18, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Daniel Martínez-Ávila </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:42</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_17.pdf\"]', '2024-05-30 20:37:42', 0),
(70, 17, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Cristina Dotta Ortega</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:45</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_16.pdf\"]', '2024-05-30 20:37:45', 0),
(71, 71, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Cibele Araujo Camargo Marques dos Santos</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:47</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_70.pdf\"]', '2024-05-30 20:37:47', 0),
(72, 14, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Célia da Consolação Dias</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:50</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_13.pdf\"]', '2024-05-30 20:37:50', 0),
(73, 13, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Carlos Henrique Marcondes de Almeida</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:52</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_12.pdf\"]', '2024-05-30 20:37:52', 0),
(74, 12, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Carla Maria Martellote Viola</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:55</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_11.pdf\"]', '2024-05-30 20:37:55', 0),
(75, 11, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Bruno Henrique Machado</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:37:58</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_10.pdf\"]', '2024-05-30 20:37:58', 0),
(76, 10, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Bruna Bomfim Lessa dos Santos</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:01</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_9.pdf\"]', '2024-05-30 20:38:01', 0),
(77, 9, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Brisa Pozzi de Sousa</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:03</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_8.pdf\"]', '2024-05-30 20:38:03', 0),
(78, 7, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Benildes Coura Moreira dos Santos Maculan</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:05</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_6.pdf\"]', '2024-05-30 20:38:05', 0),
(79, 3, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Amanda Marissa Soares da Silva</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:08</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_2.pdf\"]', '2024-05-30 20:38:08', 0),
(80, 5, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Ana Cristina de Albuquerque</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:10</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_4.pdf\"]', '2024-05-30 20:38:10', 0),
(81, 69, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Ananda Feix Ribeiro</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:13</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_68.pdf\"]', '2024-05-30 20:38:13', 0),
(82, 6, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Andre Vieira de Freitas Araújo</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:16</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_5.pdf\"]', '2024-05-30 20:38:16', 0);
INSERT INTO `isko_cms` (`id_ms`, `ms_user`, `ms_subject`, `ms_message`, `ms_attached`, `ms_data`, `ms_status`) VALUES
(83, 8, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Brígida Maria Nogueira Cervantes </b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:18</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_7.pdf\"]', '2024-05-30 20:38:18', 0),
(84, 27, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Icléia Thiesen</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:22</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_26.pdf\"]', '2024-05-30 20:38:22', 0),
(85, 29, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Jéssica dos Santos Gonçalves</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:26</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_28.pdf\"]', '2024-05-30 20:38:26', 0),
(86, 30, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Johanna Wilhelmina Smit</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:29</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_29.pdf\"]', '2024-05-30 20:38:29', 0),
(87, 52, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Rita do Carmo Ferreira Laipelt</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:33</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_51.pdf\"]', '2024-05-30 20:38:33', 0),
(88, 66, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Zaira Regina Zafalon</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-05-30 15:38:37</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/05\\/recibo_65.pdf\"]', '2024-05-30 20:38:37', 0),
(89, 63, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>Thiago Henrique Bragato Barros</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-06-03 12:18:04</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/06\\/recibo_62.pdf\"]', '2024-06-03 17:18:04', 0),
(90, 32, '[ISKOBrazil] Pagamento da Anuidade e Acesso Liberado à Revista ISKO Brasil', 'Prezada(o) <b>José Augusto Chaves Guimarães</b>,\r\n\n\r<p>Esperamos que este e-mail lhe encontre bem.</p><p>Gostaríamos de agradecer pelo pagamento da anuidade da ISKO Brasil. Sua contribuição é essencial para o fortalecimento e crescimento da nossa comunidade, permitindo-nos continuar promovendo a pesquisa e o desenvolvimento na área de Organização do Conhecimento.</p><p>Temos o prazer de informar que, com o pagamento da anuidade, seu acesso à revista da ISKO Brasil está agora liberado através da plataforma Nomos. Você poderá acessar todo o conteúdo disponível, incluindo artigos, publicações e outros recursos valiosos para sua prática e pesquisa.</p><p>Para maiores informações sobre o acesso a Revista KO, acesse <a href=\"https://isko.org.br/acesso-a-revista-knowledge-organization/\">https://isko.org.br/acesso-a-revista-knowledge-organization/</a></p><p>Se tiver qualquer dúvida ou precisar de assistência, por favor, não hesite em nos contatar.</p><p>Mais uma vez, agradecemos seu apoio e esperamos que aproveite os benefícios da sua associação.</p><br><p>Atenciosamente,</p><p><b>Rene Faustino Gabriel Junior</b><br>Tesoureiro da ISKO Brazil<br>Gestão 2024-2025<br>2024-06-03 13:59:38</p>\n\r', '[\"\\/home2\\/iskoor95\\/public_html\\/.tmp\\/recibo_2024\\/06\\/recibo_31.pdf\"]', '2024-06-03 18:59:38', 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
