INSERT INTO `instituicoes_ror` (`nome`) VALUES
('Universidade de São Paulo (USP)'),
('Universidade Estadual de Campinas (UNICAMP)'),
('Universidade Estadual Paulista (UNESP)'),
('Universidade Federal do Rio de Janeiro (UFRJ)'),
('Universidade Federal de Minas Gerais (UFMG)'),
('Universidade Federal do Rio Grande do Sul (UFRGS)'),
('Universidade Federal de Santa Catarina (UFSC)'),
('Universidade Federal do Paraná (UFPR)'),
('Universidade Federal de Pernambuco (UFPE)'),
('Universidade Federal da Bahia (UFBA)'),
('Universidade Federal do Ceará (UFC)'),
('Universidade Federal de Goiás (UFG)'),
('Universidade Federal do Pará (UFPA)'),
('Universidade Federal do Espírito Santo (UFES)'),
('Universidade Federal de São Carlos (UFSCar)'),
('Universidade Federal de Uberlândia (UFU)'),
('Universidade Federal de Viçosa (UFV)'),
('Universidade Federal de Juiz de Fora (UFJF)'),
('Universidade Federal do Rio Grande do Norte (UFRN)'),
('Universidade Federal de Alagoas (UFAL)'),
('Universidade Federal do Maranhão (UFMA)'),
('Universidade Federal da Paraíba (UFPB)'),
('Universidade Federal de Sergipe (UFS)'),
('Universidade Federal do Amazonas (UFAM)'),
('Universidade Federal do Mato Grosso (UFMT)'),
('Universidade Federal do Mato Grosso do Sul (UFMS)'),
('Universidade Federal de Pelotas (UFPel)'),
('Universidade Federal de Ouro Preto (UFOP)'),
('Universidade Federal de Lavras (UFLA)'),
('Universidade Federal de Itajubá (UNIFEI)');
